sudo: false

language: node_js

node_js:
  - 7

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@latest
  - npm install

addons:
  code_climate:
    repo_token: 070a6c56b4a8bf7ff5198ed8f0edfd2944fe773058f2ef3f581c08f3d1220ef0
